language: minimal

jobs:
  include:
    - stage: Preprod
      name: "Preprod Deployment"
      script:
        - echo "Deploying to preprod..."
        - curl -X POST -d '{}' -H 'Content-Type: application/json' -H 'Authorization: Bearer kL15Hy1hoMDnmIVb-YIYO1My1EXE4QjAmdQ2-GxVGtw' https://api.netlify.com/build_hooks/NETLIFY_PREPROD_HOOK_ID

    - stage: Prod
      name: "Prod Deployment"
      script:
        - echo "Deploying to prod..."
        - curl -X POST -d '{}' -H 'Content-Type: application/json' -H 'Authorization: Bearer kL15Hy1hoMDnmIVb-YIYO1My1EXE4QjAmdQ2-GxVGtw' https://api.netlify.com/build_hooks/NETLIFY_PROD_HOOK_ID
